### PR TITLE
Add node-sass filter

### PR DESCRIPTION
**Pull request by gremo**

### CODE REVIEW

**Comment by stof** [comment]
filters cannot be accepted without tests

**Comment by gremo** [comment]
@stof I'll write and try again, thanks.

**Comment by Ninir** [comment]
@gremo Any news on this? :-)

**Comment by gremo** [comment]
@Ninir sorry, no time atm to write tests. I would be very happy if anyone can fork and make this filter. Bootstrsap 4 is on its way...

**Comment by gremo** [comment]
Updated with tests, see #812

**Pull request closed without merging**
