### PR TITLE
Added CleanCss 2.2.x filter support

### PR DESCRIPTION
**Pull request by thetiby**
This is an update to @eXtreme's [PR](https://github.com/kriswallsmith/assetic/pull/476), removing conflicts and adding support for all clean-css v2.2.x options.
Thanks for taking the initiative @eXtreme!

### CODE REVIEW

**Comment by thetiby** [comment]
@stof Hi there, can you merge this one please? I got rid of all conflicts again.

**Comment by niksy** [comment]
Any chance of getting this in main repo?

**Comment by thetiby** [comment]
@kriswallsmith does this PR miss anything? can you merge it?

**Comment by guill3m** [comment]
What is the status in this PR?

Are there any plans on merging it to the main repo?

**Pull request closed without merging**
