### PR TITLE
Throw an exception on template errors when using Twig strict_variable…

### PR DESCRIPTION
**Pull request by guillaumelecerf**
…s configuration

### CODE REVIEW

**Comment by stof** [comment]
this looks wrong to me. It should depend on what the exception is.

A syntax error in the template should not prevent looking at following templates. Only exceptions coming from Assetic (wrong asset) should be rethrow here

**Comment by kmelia** [comment]
Hi,

> It should depend on what the exception is.

The exception is thrown by the Twig environment, so it could be anything.

Any error in a Twig template (with the ``strict_variables: true``) should be rised to the user!

**Comment by stof** [comment]
@kmelia Twig wraps the exceptions in its own exception, that's true. But it is still possible to find the original one.

and no, re-triggering all exceptions to the user here is a very bad idea. If you have a template which uses an undefined filter (because it is meant to be used only when a specific feature is enabled and it is not currently), your suggestion would make it impossible to extract formulae from templates even though this template does not contain any, because it would stop the process.
This is why we are logging errors (to make debugging easier), but we don't consider them as blockers (most templates generally don't contain Assetic tags).
the goal of the Assetic loader is not to act as a linter for all your Twig templates

**Comment by stof** [comment]
and btw, ``strict_variables`` has nothing to do with this behavior: it is flag affecting the runtime behavior of Twig, and we don't reach the point where it is used by Twig here as we only parse templates

**Comment by kmelia** [comment]
> we only parse templates

It parses templates with a ``Twig_Environment``. So we could consider the parsing with the specificity of the Twig environment: strict or not.

**Comment by stof** [comment]
@kmelia but strict_variables has strictly **no effect** on the parsing of a template. It has effect on the error handling when **rendering** a template

**Pull request closed without merging**
