### PR TITLE
Adding a ; between the dumped files

### PR DESCRIPTION
**Pull request by bloveless**
will allow files that don't end properly or with a semicolon to be combined without error.

### CODE REVIEW

**Comment by kriswallsmith** [comment]
You can do this using SeparatorFilter.

**Comment by bloveless** [comment]
Didn't see that. Thanks!

**Comment by RyanThompson** [comment]
Doesn't look like that file is in a tagged release? What's the scoop on that?

**Comment by kriswallsmith** [comment]
Good point. I'll get another release out soon.

**Comment by RyanThompson** [comment]
Sweet deal, thank you!


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is<http://www.anomaly.is>

t (877) 705-0806
m (309) 752-8581



On Jul 8, 2015, at 3:27 PM, Kris Wallsmith <notifications@github.com<mailto:notifications@github.com>> wrote:

Good point. I'll get another release out soon.

**Comment by RyanThompson** [comment]
Do you have a target for the next tag? I've got a beta release this month Ill hold off on some changes if you're thinking soon-ish.

**Pull request closed without merging**
