### PR TITLE
Update the lowest bound of the Twig dev requirement

### PR DESCRIPTION
**Pull request by Titome**
I fix it a Twig depreciation, see https://github.com/twigphp/Twig/commit/e3a325f249a5ff4cdbbabbec7271c13dee2d7ac5 for more information.

Thanks

### CODE REVIEW

**Comment by stof** [comment]
you need to bump the min Twig version though

**Comment by Titome** [comment]
Hum sorry, I'm not used to collaborate at projects... Where I need to bump the min Twig version ? In the composer.json ? Thank for your help.

**Comment by stof** [comment]
yes

**Comment by Titome** [comment]
I update the composer.json :)

**Comment by stof** [comment]
please rebase your branch to fix conflicts

**Comment by Titome** [comment]
Done! :)

**Comment by stof** [comment]
Most change have actually disappeared because of the merge of https://github.com/kriswallsmith/assetic/pull/772

I will still merge this PR to update the lowest bound of the dev requirement

**Comment by stof** [comment]
Thank you @Titome.

**Pull request closed without merging**
